[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = [
  'pnpm install --frozen-lockfile --ignore-scripts'
]

[phases.build]
cmds = [
  'cd packages/shared && tsc --build',
  'cd apps/worker && tsc --build'
]

[start]
cmd = 'cd apps/worker && node dist/index.js'

# Disable automatic framework detection
[variables]
NIXPACKS_NO_MUSL = '1'
